//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWebLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Cliente
    {
        public int IdCliDet { get; set; }
        public Nullable<int> IdCli { get; set; }
        public Nullable<decimal> Sue { get; set; }
        public Nullable<int> NumHij { get; set; }
        public string EstCiv { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
