//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWebLogin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistWebLoginEnti : DbContext
    {
        public SistWebLoginEnti()
            : base("name=SistWebLoginEnti")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NuevaTareaPersonalizada> NuevaTareaPersonalizada { get; set; }
        public virtual DbSet<NuevaTareaSimple> NuevaTareaSimple { get; set; }
        public virtual DbSet<TipoTarea> TipoTarea { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
