//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWebLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NuevaTareaSimple
    {
        public int IdTarSim { get; set; }
        public Nullable<System.DateTime> FecTar { get; set; }
        public Nullable<int> IdUsu { get; set; }
        public Nullable<int> IdTip { get; set; }
        public string DesTar { get; set; }
        public string TitTar { get; set; }
    
        public virtual TipoTarea TipoTarea { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
