//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWebLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoTarea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoTarea()
        {
            this.NuevaTareaPersonalizada = new HashSet<NuevaTareaPersonalizada>();
            this.NuevaTareaSimple = new HashSet<NuevaTareaSimple>();
        }
    
        public int IdTip { get; set; }
        public string NomTip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NuevaTareaPersonalizada> NuevaTareaPersonalizada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NuevaTareaSimple> NuevaTareaSimple { get; set; }
    }
}
